image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      python -m pip install urubu
      source ~/.bashrc
ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
